// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Sample",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v17)
    ],
    products: [
        .iOSApplication(
            name: "Sample",
            targets: ["Sample"],
            bundleIdentifier: "com.igorcferreira.gifimage.sample",
            teamIdentifier: "V5F865B4U5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .images),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeLeft,
                .landscapeRight,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .outgoingNetworkConnections(),
                .fileAccess(.userSelectedFiles, mode: .readOnly)
            ],
            appCategory: .developerTools
        )
    ],
    dependencies: [
        .package(url: "../", from: "1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "Sample",
            dependencies: [
                .product(name: "GIFImage", package: "gifimage")
            ],
            path: ".",
            resources: [
                .process("test.gif")
            ]
        )
    ]
)
